[[main]]
name = "Posts"
pageRef = "posts"
weight = 10

[[main]]
name = "Tags"
pageRef = "tags"
weight = 20

[[main]]
identifier = "web"
pre = "link"
url = "https://nunocoracao.github.io/blowfish/"
weight = 40

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/nunocoracao/blowfish"
weight = 50

[[main]]
identifier = "twitter"
pre = "twitter"
url = "https://twitter.com/burufugu"
weight = 60


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10