defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
colorScheme = "noir"

mainSections = ["posts"]

[header]
layout = "fixed" # valid options: basic, fixed

[footer]
# showMenu = true
showCopyright = false
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background" # valid options: page, profile, hero, card, background, custom
homepageImage = "img/cover.png" # used in: hero, and card
showRecent = true
showRecentItems = 3
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true # only used when layout equals background

[article]
showDate = true
#showViews = true
#showLikes = true
showDateUpdated = false
#showAuthor = true
showHero = true
heroStyle = "background" # valid options: basic, big, background
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
# editURL = "https://github.com/username/repo/"
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = true

[list]
showHero = true
heroStyle = "background" # valid options: basic, big, background
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true